#!/usr/bin/env python3
"""
Sync shared/fmp_base.py into each skill's scripts/fmp_client.py.

Run this after editing shared/fmp_base.py to propagate changes:
    python3 scripts/sync_fmp_client.py

Skills are kept self-contained (no parent-path imports) while
shared/fmp_base.py remains the single source of truth.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "shared" / "fmp_base.py"

HEADER = """\
# AUTO-SYNCED from shared/fmp_base.py — do not edit this file directly.
# To update: edit shared/fmp_base.py then run: python3 scripts/sync_fmp_client.py

"""

SKILL_CLIENTS = [
    "skills/canslim-screener/scripts/fmp_client.py",
    "skills/earnings-trade-analyzer/scripts/fmp_client.py",
    "skills/ftd-detector/scripts/fmp_client.py",
    "skills/ibd-distribution-day-monitor/scripts/fmp_client.py",
    "skills/macro-regime-detector/scripts/fmp_client.py",
    "skills/market-top-detector/scripts/fmp_client.py",
    "skills/parabolic-short-trade-planner/scripts/fmp_client.py",
    "skills/pead-screener/scripts/fmp_client.py",
    "skills/vcp-screener/scripts/fmp_client.py",
]


def main() -> int:
    if not SOURCE.exists():
        print(f"ERROR: source not found: {SOURCE}", file=sys.stderr)
        return 1

    body = SOURCE.read_text()
    synced = HEADER + body

    errors = 0
    for rel in SKILL_CLIENTS:
        dest = REPO_ROOT / rel
        if not dest.parent.exists():
            print(f"  SKIP  {rel}  (directory missing)")
            continue
        dest.write_text(synced)
        print(f"  OK    {rel}")

    if errors:
        print(f"\n{errors} error(s). Fix above and re-run.", file=sys.stderr)
    else:
        print(f"\nSynced {len(SKILL_CLIENTS)} files from {SOURCE.relative_to(REPO_ROOT)}")
    return errors


if __name__ == "__main__":
    sys.exit(main())
